### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by hamlet** [m4lvin/nextcloud-client-debian-packaging#1]
Hello, 
my system was missing a library : libQt5Concurrent.so.5
Installing package libqt5concurrent5 resolved it.
Regards

**Comment by m4lvin** [comment]
Thanks, I will add `libqt5concurrent5` to `--requires` [here](https://github.com/m4lvin/nextcloud-client-debian-packaging/blob/master/Makefile#L53) in the next release.

**Comment by robaru** [comment]
same problem for me...

resolved as hamlet pointed out!

Awesome job by the way!
Thank you!

Roberto

**Comment by m4lvin** [comment]
fixed in https://github.com/m4lvin/nextcloud-client-debian-packaging/commit/6939873e8e53968da2c33e6d1205bc5f7be62a9d
