### ISSUE TITLE
User-Configs?

### ISSUE THREAD

**Issue by BurtGummer** [m4lvin/nextcloud-client-debian-packaging#2]
Hello,

first, thank you for this Debian packages. In my home i search the config-files from this client, but found nothing, direct in ~ and in ~/.config/

Where are the settings stored?

**Comment by m4lvin** [comment]
I found my own config files at `~./.local/share/data/Nextcloud`.

Strange. Either https://docs.nextcloud.com/desktop/2.3/advancedusage.html#configuration-file is not correct or the way I build the client somehow changes the config path :thinking:

**Comment by BurtGummer** [comment]
Aah thanx very much. Yes, the path /home/USER/.local/share/data/Nextcloud exists. Little bit strange this path.. ;-)
