### ISSUE TITLE
add option to add or change server url and account info

### ISSUE THREAD

**Issue by Dutchglory** [m4lvin/nextcloud-client-debian-packaging#3]
Nextcloud client Version 2.3.3
installed from: https://m4lvin.github.io/nextcloud-client-debian-packaging/

Please add option to add or change server url and account info (username and pass)
there' s no way to re-configure nextcloud server url and account info...

**Comment by m4lvin** [comment]
I think the only way to change the server url or username is to remove the account and add a new one. For the password, the client should ask for a new password in case the current one no longer works.

Please note that I am only *packaging* the Nextcloud client here. Hence for help with the Nextcloud client itself, please check the [Nextcloud Desktop Client Manual](https://docs.nextcloud.com/desktop/2.3/) or search and ask in the [Nextcloud forums](https://help.nextcloud.com/), for example [this](https://help.nextcloud.com/t/changing-server-url-in-client/18627).

If you want to report an issue against the client, the correct repository is https://github.com/nextcloud/client_theming but soon will be https://github.com/nextcloud/desktop.
