### ISSUE TITLE
Segmentation fault when entering suspend mode with nextcloud 2.3.3 on Debian 64

### ISSUE THREAD

**Issue by logg-sar** [m4lvin/nextcloud-client-debian-packaging#4]
Hi

first I posted in https://github.com/nextcloud/desktop/issues/241 because I found an quite similar thread.
Where is it correct?

However - here is the error message:

In syslog I found this entry:

nextcloud[5458]: segfault at 7ffc19ec2ff8 ip 00007fab08cd8952 sp 00007ffc19ec3000 error 6 in libQt5Core.so.5.10.1[7fab08c25000+4ee000]

I use
Nextcloud version 2.3.3
Git revision 57bc791
Using Qt 5.10.1, built against Qt 5.7.1
Using 'OpenSSL 1.1.0h 27 Mar 2018'

PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Linux enterprise 4.15.0-2-amd64 #1 SMP Debian 4.15.11-1 (2018-03-20) x86_64 GNU/Linux
Thank you

**Comment by m4lvin** [comment]
Please note that I am only *packaging* the Nextcloud client here. Hence for help with the Nextcloud client itself, please check the Nextcloud Desktop Client Manual or search and ask in the Nextcloud forums, for example this.

If you want to report an issue against the client, the correct repository is https://github.com/nextcloud/client_theming but soon will be https://github.com/nextcloud/desktop.
